### ISSUE TITLE
Grade for Form Finalizer

### ISSUE THREAD

**Issue by riannazandbelt** [riannazandbelt/data-table#1]
@muxlowc

Attached is a screenshot of the Form Finalizer for Week 11

Cheers,
Rianna
Section 3

<img width="1025" alt="Screen Shot 2020-03-15 at 1 37 17 PM" src="https://user-images.githubusercontent.com/55094049/76897841-e241b300-686a-11ea-83f0-1eceaa10bafe.png">

**Comment by muxlowc** [comment]
@riannazandbelt  got it, thanks!!
